name: watchtower
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - salmon>=1.10
  - sra-tools>=3.0
  - fastqc
  - multiqc
  - r-base>=4.3
  - bioconductor-deseq2
  - bioconductor-clusterprofiler
  - bioconductor-org.gg.eg.db
  - nextflow>=24.04
  - pip
  - pip:
      - -e ".[dev]"
